### ISSUE TITLE
Parameter Doubts 

### ISSUE THREAD

**Issue by NiharikaVadlamudi** [megvii-research/ICCV2019-LearningToPaint#44]
Few doubts on parameters : 

Q1. Here, what is the difference between max_steps, train_times, and episode_train_times? Can you please define them?

Q2. What happens during the warmup stage?  ( Is there any issue if we keep warmup step=0)

**Comment by hzwer** [comment]
A1. max_steps means 'max length for episode', default 40 means 40 * 5 strokes to paint an image.
train_times means model the number of  update iterations during training.
episode_train_times means the number of model update iterations after every batch of finished episode.
Q2. In warmup process, we just collect training examples to fill replay memory buffer, so that at the beginning of training, the training samples are relatively rich. I think the lack of this process may slightly affect the performance of the model.
